### ISSUE TITLE
Please provide AppImage for Linux on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [deislabs/duffle-bag#51]
https://github.com/deislabs/duffle-bag/blob/e1240ef1428673964d524146f9e6300a4d794e0a/package.json#L104

Please provide an AppImage for Linux on GitHub Releases, thanks.

**Comment by itowlson** [comment]
Can you clarify the request please?  This is a _template_ for applications, not an application that should be released in itself; our 'releases' are really source code snapshots identifying the commits that code generators should use.  (Perhaps they should be tags rather than 'releases'.)  With that clarification, is there still value in an AppImage release?

**Comment by probonopd** [comment]
I see, thanks for your clarification.
